# Generated by Django 3.1.4 on 2021-01-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WHO_region', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('Population_at_risk', models.IntegerField()),
                ('Cases', models.IntegerField()),
                ('Deaths', models.IntegerField()),
            ],
        ),
    ]
