# Generated by Django 3.1.4 on 2021-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malaria',
            name='GDP_per_capita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='malaria',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='malaria',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=13),
        ),
        migrations.AddField(
            model_name='malaria',
            name='Rainfall_gauge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='malaria',
            name='Rural_pop_pct',
            field=models.IntegerField(default=0),
        ),
    ]
